'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARTBOPTCALC_FINGERPRINTS
    Public Property PRODUCT_ID As String
    Public Property FINGER_PRINT As String
    Public Property COMPUTER_NAME As String
    Public Property ACTIVE As Boolean
    Public Property DEMO_EXPIRATION_DATE As Date
    Public Property HIDE As Boolean
    Public Property LICENSE_KEY As String
    Public Property OFID As String
    Public Property UPDATER As Boolean
    Public Property PRICER As Boolean

    Public Overridable Property ARTBOPTCALC_LICENSES As ARTBOPTCALC_LICENSES
    Public Overridable Property ARTBOPTCALC_PRODUCTS As ARTBOPTCALC_PRODUCTS

End Class
