'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARTBOPTCALC_LICENSES
    Public Property ID As Integer
    Public Property LICENSE_KEY As String
    Public Property PRODUCT_ID As String
    Public Property DEMO As Boolean
    Public Property MAX_LICENSES As Integer
    Public Property USED_LICENSES As Integer
    Public Property LICENSE_PURCH_DATE As Nullable(Of Date)
    Public Property LICENSE_EXP_DATE As Nullable(Of Date)
    Public Property REG_NAME As String
    Public Property EMAIL As String
    Public Property FIRSTNAME As String
    Public Property LASTNAME As String
    Public Property COMPANY As String
    Public Property COUNTRY As String
    Public Property PURCHASE_ID As String
    Public Property BROKER As Boolean

    Public Overridable Property ARTBOPTCALC_FINGERPRINTS As ICollection(Of ARTBOPTCALC_FINGERPRINTS) = New HashSet(Of ARTBOPTCALC_FINGERPRINTS)
    Public Overridable Property ARTBOPTCALC_PRODUCTS As ARTBOPTCALC_PRODUCTS

End Class
