'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARTBOPTCALC_PRODUCTS
    Public Property PRODUCT_ID As String
    Public Property ACTIVE As Boolean
    Public Property CCY_ID As Integer
    Public Property BASE_PRICE As Double
    Public Property DISCOUNTS As Boolean
    Public Property DISC_TIER1 As Integer
    Public Property DISC_PRC1 As Double
    Public Property DISC_TIER2 As Integer
    Public Property DISC_PRC2 As Double
    Public Property DISC_TIER3 As Integer
    Public Property DISC_PRC3 As Double
    Public Property DISC_TIER4 As Integer
    Public Property DISC_PRC4 As Double

    Public Overridable Property ARTBOPTCALC_FINGERPRINTS As ICollection(Of ARTBOPTCALC_FINGERPRINTS) = New HashSet(Of ARTBOPTCALC_FINGERPRINTS)
    Public Overridable Property ARTBOPTCALC_LICENSES As ICollection(Of ARTBOPTCALC_LICENSES) = New HashSet(Of ARTBOPTCALC_LICENSES)

End Class
