'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BALTIC_FTP
    Public Property ID As Integer
    Public Property ROUTE_ID As Integer
    Public Property CMSROUTE_ID As String
    Public Property PERIOD As String
    Public Property QUALIFIER As String

    Public Overridable Property BALTIC_FORWARD_RATES As ICollection(Of BALTIC_FORWARD_RATES) = New HashSet(Of BALTIC_FORWARD_RATES)
    Public Overridable Property ROUTES As ROUTES
    Public Overridable Property BALTIC_OPTION_VOLATILITIES As ICollection(Of BALTIC_OPTION_VOLATILITIES) = New HashSet(Of BALTIC_OPTION_VOLATILITIES)

End Class
