'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BALTIC_OPTION_VOLATILITIES
    Public Property ROUTE_ID As Integer
    Public Property CMSROUTE_ID As String
    Public Property FIXING_DATE As Date
    Public Property NEXT_ROLLOVER_DATE As Date
    Public Property FIXING As Double
    Public Property REPORTDESC As String
    Public Property MM1 As Nullable(Of Short)
    Public Property YY1 As Nullable(Of Short)
    Public Property MM2 As Nullable(Of Short)
    Public Property YY2 As Nullable(Of Short)
    Public Property PERIOD As String
    Public Property YY As Nullable(Of Integer)

    Public Overridable Property BALTIC_FTP As BALTIC_FTP
    Public Overridable Property ROUTES As ROUTES

End Class
