'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TRADE_CLASSES
    Public Property TRADE_CLASS_SHORT As String
    Public Property TRADE_CLASS As String
    Public Property TRADE_CLASS_DES As String

    Public Overridable Property VESSEL_CLASS As ICollection(Of VESSEL_CLASS) = New HashSet(Of VESSEL_CLASS)

End Class
