'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ARTBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ARTBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property ARTBOPTCALC_FINGERPRINTS() As DbSet(Of ARTBOPTCALC_FINGERPRINTS)
    Public Property ARTBOPTCALC_LICENSES() As DbSet(Of ARTBOPTCALC_LICENSES)
    Public Property ARTBOPTCALC_PRODUCTS() As DbSet(Of ARTBOPTCALC_PRODUCTS)
    Public Property BALTIC_FORWARD_RATES() As DbSet(Of BALTIC_FORWARD_RATES)
    Public Property BALTIC_FTP() As DbSet(Of BALTIC_FTP)
    Public Property BALTIC_FTP_SETTLEMENT() As DbSet(Of BALTIC_FTP_SETTLEMENT)
    Public Property BALTIC_MONTHLY_SETTLEMENTS() As DbSet(Of BALTIC_MONTHLY_SETTLEMENTS)
    Public Property BALTIC_OPTION_VOLATILITIES() As DbSet(Of BALTIC_OPTION_VOLATILITIES)
    Public Property BALTIC_SPOT_RATES() As DbSet(Of BALTIC_SPOT_RATES)
    Public Property ROUTES() As DbSet(Of ROUTES)
    Public Property TRADE_CLASSES() As DbSet(Of TRADE_CLASSES)
    Public Property VESSEL_CLASS() As DbSet(Of VESSEL_CLASS)
    Public Property VESSEL_CLASS_SPREAD_MARGINS() As DbSet(Of VESSEL_CLASS_SPREAD_MARGINS)

End Class
