'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BALTIC_SPOT_RATES
    Public Property ROUTE_ID As Integer
    Public Property FIXING_DATE As Date
    Public Property FIXING As Double

    Public Overridable Property ROUTES As ROUTES

End Class
