'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ROUTES
    Public Property ROUTE_ID As Integer
    Public Property VESSEL_CLASS_ID As Integer
    Public Property QUOTE_TYPE As Short
    Public Property QUANTITY_TYPE As Short
    Public Property CCY_ID As Nullable(Of Integer)
    Public Property ROUTE_SHORT As String
    Public Property ROUTE_DESCR As String
    Public Property BALTIC_ABRV As String
    Public Property BALTIC_ABRV_FFA As String
    Public Property SETTLEMENT_TYPE As Short
    Public Property LOT_SIZE As Integer
    Public Property SETTLEMENT_TICK As Double
    Public Property PRICING_TICK As Double
    Public Property FULL_LOT_SIZE As Integer
    Public Property FFA_TRADED As Boolean
    Public Property LAST_DAY_RULE_ID As Integer
    Public Property DEFAULT_QUANTITY As Double
    Public Property SETTL_ROUTE_ID As Integer
    Public Property OPTIONS_TRADED As Boolean

    Public Overridable Property BALTIC_FORWARD_RATES As ICollection(Of BALTIC_FORWARD_RATES) = New HashSet(Of BALTIC_FORWARD_RATES)
    Public Overridable Property BALTIC_FTP As ICollection(Of BALTIC_FTP) = New HashSet(Of BALTIC_FTP)
    Public Overridable Property BALTIC_FTP_SETTLEMENT As ICollection(Of BALTIC_FTP_SETTLEMENT) = New HashSet(Of BALTIC_FTP_SETTLEMENT)
    Public Overridable Property BALTIC_MONTHLY_SETTLEMENTS As ICollection(Of BALTIC_MONTHLY_SETTLEMENTS) = New HashSet(Of BALTIC_MONTHLY_SETTLEMENTS)
    Public Overridable Property BALTIC_OPTION_VOLATILITIES As ICollection(Of BALTIC_OPTION_VOLATILITIES) = New HashSet(Of BALTIC_OPTION_VOLATILITIES)
    Public Overridable Property BALTIC_SPOT_RATES As ICollection(Of BALTIC_SPOT_RATES) = New HashSet(Of BALTIC_SPOT_RATES)
    Public Overridable Property VESSEL_CLASS As ICollection(Of VESSEL_CLASS) = New HashSet(Of VESSEL_CLASS)
    Public Overridable Property VESSEL_CLASS_SPREAD_MARGINS As ICollection(Of VESSEL_CLASS_SPREAD_MARGINS) = New HashSet(Of VESSEL_CLASS_SPREAD_MARGINS)

End Class
