'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VESSEL_CLASS
    Public Property VESSEL_CLASS_ID As Integer
    Public Property VESSEL_CLASS1 As String
    Public Property DRYWET As String
    Public Property WETSECTOR As String
    Public Property DESCRIPTION As String
    Public Property DEFAULT_ROUTE_ID As Nullable(Of Integer)

    Public Overridable Property ROUTES As ROUTES
    Public Overridable Property TRADE_CLASSES As TRADE_CLASSES

End Class
