'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VESSEL_CLASS_SPREAD_MARGINS
    Public Property VESSEL_CLASS_ID As Integer
    Public Property ROUTE_ID As Integer
    Public Property CMSROUTE_ID As String
    Public Property MM1 As Short
    Public Property YY1 As Short
    Public Property MM2 As Short
    Public Property YY2 As Short
    Public Property PERIOD As String
    Public Property YY As Integer
    Public Property MARGIN As Double

    Public Overridable Property ROUTES As ROUTES

End Class
