'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.artbtrading.com/ArtBwcfData/ArtBwcfDataService.svc")>  _
        Public ReadOnly Property ServicePathLive() As String
            Get
                Return CType(Me("ServicePathLive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.artbtrading.com/ArtBwcfData/ArtBwcfDataService.svc")>  _
        Public ReadOnly Property ServicePathDebug() As String
            Get
                Return CType(Me("ServicePathDebug"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2908")>  _
        Public ReadOnly Property PRODUCT_ID() As String
            Get
                Return CType(Me("PRODUCT_ID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>787F9C7CA71AD09949025059BB47C369</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>E24DD330841A0CBA48EBF"& _ 
            "47829A64377</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>2B1F2C9E2426FC3D</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public ReadOnly Property ValidCertificates() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ValidCertificates"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("retxed")>  _
        Public ReadOnly Property DogHouse() As String
            Get
                Return CType(Me("DogHouse"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3228427")>  _
        Public Property ClickATell_API_ID() As String
            Get
                Return CType(Me("ClickATell_API_ID"),String)
            End Get
            Set
                Me("ClickATell_API_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("pearlharbor1")>  _
        Public Property ClickATell_Password() As String
            Get
                Return CType(Me("ClickATell_Password"),String)
            End Get
            Set
                Me("ClickATell_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BRSFFA")>  _
        Public Property ClickATell_UserName() As String
            Get
                Return CType(Me("ClickATell_UserName"),String)
            End Get
            Set
                Me("ClickATell_UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BRS")>  _
        Public Property ClickATell_SMSFrom() As String
            Get
                Return CType(Me("ClickATell_SMSFrom"),String)
            End Get
            Set
                Me("ClickATell_SMSFrom") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=hipathsystems.cloudapp.net,5223;Initial Catalog=ARTB;Persist Security"& _ 
            " Info=True;User ID=gmf;Password=@egean@ndr0s")>  _
        Public ReadOnly Property ConnectionString_BRS2() As String
            Get
                Return CType(Me("ConnectionString_BRS2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ConnectionString_BRS2UserOverride() As String
            Get
                Return CType(Me("ConnectionString_BRS2UserOverride"),String)
            End Get
            Set
                Me("ConnectionString_BRS2UserOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=hipathsystems.cloudapp.net,5223;Initial Catalog=ARTB;Persist Security"& _ 
            " Info=True;User ID=gmf;Password=@egean@ndr0s;Network Library=dbmssocn")>  _
        Public ReadOnly Property ConnectionString_EXTERNAL() As String
            Get
                Return CType(Me("ConnectionString_EXTERNAL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RememberMe() As Boolean
            Get
                Return CType(Me("RememberMe"),Boolean)
            End Get
            Set
                Me("RememberMe") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=hipathsystems.cloudapp.net,5223;Initial Catalog=ARTB;Persist Security"& _ 
            " Info=True;User ID=gmf;Password=@egean@ndr0s")>  _
        Public ReadOnly Property ConnectionString_BRS() As String
            Get
                Return CType(Me("ConnectionString_BRS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CheckBoxConnection() As Integer
            Get
                Return CType(Me("CheckBoxConnection"),Integer)
            End Get
            Set
                Me("CheckBoxConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ffa@brsbrokers.com")>  _
        Public Property TxtLocal_UserName() As String
            Get
                Return CType(Me("TxtLocal_UserName"),String)
            End Get
            Set
                Me("TxtLocal_UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("pearlharbor1")>  _
        Public Property TxtLocal_Password() As String
            Get
                Return CType(Me("TxtLocal_Password"),String)
            End Get
            Set
                Me("TxtLocal_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property SMS_SafetyBalance() As Integer
            Get
                Return CType(Me("SMS_SafetyBalance"),Integer)
            End Get
            Set
                Me("SMS_SafetyBalance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BRS")>  _
        Public Property TxtLocalSender() As String
            Get
                Return CType(Me("TxtLocalSender"),String)
            End Get
            Set
                Me("TxtLocalSender") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.artbtrading.com/WSFFASuiteServer/websync.ashx")>  _
        Public Property ws_ServerLive() As String
            Get
                Return CType(Me("ws_ServerLive"),String)
            End Get
            Set
                Me("ws_ServerLive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.artbtrading.com/WSFFASuiteServer/websync.ashx")>  _
        Public Property ws_ServerDemo() As String
            Get
                Return CType(Me("ws_ServerDemo"),String)
            End Get
            Set
                Me("ws_ServerDemo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/my/trades")>  _
        Public Property ws_TradesChannel() As String
            Get
                Return CType(Me("ws_TradesChannel"),String)
            End Get
            Set
                Me("ws_TradesChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("barry-user@transfer.balticarray.com")>  _
        Public Property BalticUser() As String
            Get
                Return CType(Me("BalticUser"),String)
            End Get
            Set
                Me("BalticUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sWhXZvQJ0I")>  _
        Public Property BalticPassword() As String
            Get
                Return CType(Me("BalticPassword"),String)
            End Get
            Set
                Me("BalticPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=BRS2;Initial Catalog=ARTB;User ID=george;Password=Pass1234")>  _
        Public ReadOnly Property ConnectionString_BRS2_Old() As String
            Get
                Return CType(Me("ConnectionString_BRS2_Old"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=BRS2;Initial Catalog=ARTB;User ID=george;Password=Pass1234")>  _
        Public Property ConnectionString_BRS_old() As String
            Get
                Return CType(Me("ConnectionString_BRS_old"),String)
            End Get
            Set
                Me("ConnectionString_BRS_old") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FFASuiteUpdater.My.MySettings
            Get
                Return Global.FFASuiteUpdater.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
